name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON File
        id: read-json
        run: |
          echo "Reading JSON File..."
          jsonData=$(cat config.json)
          clientId=$(echo $jsonData | jq -r '.clientId')
          clientSecret=$(echo $jsonData | jq -r '.clientSecret')
          echo "ClientID: $clientId"
          echo "ClientSecret: $clientSecret"
        shell: bash

      - name: Use Extracted Values
        run: |
          echo "Using ClientID: $CLIENT_ID"
          echo "Using ClientSecret: $CLIENT_SECRET"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
